AWSTemplateFormatVersion: '2010-09-09'
Description: 'RevHub ECS Task Definitions and Services'

Parameters:
  ClusterName:
    Type: String
    Default: RevHub-Cluster
    Description: ECS Cluster Name
  
  ECRRegistry:
    Type: String
    Description: ECR Registry URL (e.g., 123456789012.dkr.ecr.us-east-1.amazonaws.com)
  
  DatabaseEndpoint:
    Type: String
    Description: RDS MySQL Endpoint
  
  VPCId:
    Type: String
    Description: VPC ID
  
  PrivateSubnet1:
    Type: String
    Description: Private Subnet 1 ID
  
  PrivateSubnet2:
    Type: String
    Description: Private Subnet 2 ID

Resources:
  # Task Execution Role
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # API Gateway Task Definition
  APIGatewayTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: revhub-api-gateway
      NetworkMode: bridge
      RequiresCompatibilities:
        - EC2
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      ContainerDefinitions:
        - Name: api-gateway
          Image: !Sub ${ECRRegistry}/revhub/api-gateway:latest
          Memory: 512
          PortMappings:
            - ContainerPort: 8080
              HostPort: 0
              Protocol: tcp
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: aws
            - Name: CONSUL_HOST
              Value: consul.revhub.local
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/revhub-api-gateway
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  # User Service Task Definition
  UserServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: revhub-user-service
      NetworkMode: bridge
      RequiresCompatibilities:
        - EC2
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      ContainerDefinitions:
        - Name: user-service
          Image: !Sub ${ECRRegistry}/revhub/user-service:latest
          Memory: 512
          PortMappings:
            - ContainerPort: 8081
              HostPort: 0
              Protocol: tcp
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: aws
            - Name: DB_HOST
              Value: !Ref DatabaseEndpoint
            - Name: DB_NAME
              Value: revhub
            - Name: CONSUL_HOST
              Value: consul.revhub.local
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/revhub-user-service
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  # Post Service Task Definition
  PostServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: revhub-post-service
      NetworkMode: bridge
      RequiresCompatibilities:
        - EC2
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      ContainerDefinitions:
        - Name: post-service
          Image: !Sub ${ECRRegistry}/revhub/post-service:latest
          Memory: 512
          PortMappings:
            - ContainerPort: 8082
              HostPort: 0
              Protocol: tcp
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: aws
            - Name: DB_HOST
              Value: !Ref DatabaseEndpoint
            - Name: DB_NAME
              Value: revhub
            - Name: CONSUL_HOST
              Value: consul.revhub.local
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/revhub-post-service
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  # ECS Services
  APIGatewayService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: revhub-api-gateway
      Cluster: !Ref ClusterName
      TaskDefinition: !Ref APIGatewayTaskDefinition
      DesiredCount: 2
      LaunchType: EC2
      LoadBalancers:
        - ContainerName: api-gateway
          ContainerPort: 8080
          TargetGroupArn: !Ref ALBTargetGroup
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50

  UserServiceService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: revhub-user-service
      Cluster: !Ref ClusterName
      TaskDefinition: !Ref UserServiceTaskDefinition
      DesiredCount: 2
      LaunchType: EC2
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50

  PostServiceService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: revhub-post-service
      Cluster: !Ref ClusterName
      TaskDefinition: !Ref PostServiceTaskDefinition
      DesiredCount: 2
      LaunchType: EC2
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50

  # CloudWatch Log Groups
  APIGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/revhub-api-gateway
      RetentionInDays: 7

  UserServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/revhub-user-service
      RetentionInDays: 7

  PostServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/revhub-post-service
      RetentionInDays: 7

  # Target Group for Load Balancer
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: RevHub-API-TG
      Port: 8080
      Protocol: HTTP
      VpcId: !Ref VPCId
      HealthCheckPath: /actuator/health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      TargetType: instance

Outputs:
  APIGatewayServiceArn:
    Description: API Gateway Service ARN
    Value: !Ref APIGatewayService
  
  UserServiceServiceArn:
    Description: User Service ARN
    Value: !Ref UserServiceService
  
  PostServiceServiceArn:
    Description: Post Service ARN
    Value: !Ref PostServiceService